import pandas as pd

df = pd.read_csv('../data/salaries.csv')
print(df)
print('-------------')
print(df['Name'])
print('-------------')
print(df[['Name','Salary']])
print('-------------')
print(df['Salary'].min())
print(df['Salary'].max())
print(df['Salary'].mean())
print('-------------')
print(df)
print('-------------')
series_of_bool = df['Age'] > 30
print(series_of_bool)
print('-------------')
print(df[series_of_bool])
print('-------------')
print(df['Age'].unique())
print('-------------')
print(df['Age'].nunique())
print('-------------')
print(df.columns)
print('-------------')
print(df.info())
print('-------------')
print(df.describe())
print('-------------')
print(df.index)
print('-------------')
print('-------------')
